### ISSUE TITLE
Start adding to do items to the project task list

### ISSUE THREAD

**Issue by mbcann01** [mbcann01/waiver_evaluation#1]
As the first step in this process, please do the following:

- [ ] Quickly read up on [GitHub issues](https://guides.github.com/features/issues/)

- [ ] Quickly read up on [GitHub projects](https://help.github.com/articles/about-project-boards/)

- [ ] Use that document Dr. Livingston sent us to start mapping out the steps needed to complete this project in the [project task list](https://github.com/brad-cannell/waiver_evaluation/projects/1)
